### PR TITLE
filter db by date

### PR DESCRIPTION
**Pull request by BobBorges**
Filter the db by date when detecting ministers. This is handy when we have the role and date but not a name.

### CODE REVIEW

**Comment by BobBorges** [comment]
Is sth wrong (?) with the notebook? @ninpnin

**Comment by ninpnin** [comment]
politicians -> persons

**Comment by ninpnin** [comment]
LGTM. In the future, we want to use logging / trainerlog , so that it's easy to turn prints on and off.

**Comment by ninpnin** [comment]
Should we make the notebook update the date / version every time we merge to main?

**Comment by BobBorges** [comment]
That would be most professional.

**Pull request merged**
