### PR TITLE
add prerelease workflow

### PR DESCRIPTION
**Pull request by BobBorges**
automatically bump version number (cff, docs) and buld documentation on PR to main

closes swerik-project/the-swedish-parliament-corpus#39

### CODE REVIEW

**Comment by BobBorges** [comment]
> Could we use this https://pypi.org/project/semantic-version/ or this https://pypi.org/project/semver/

Some CLI tool would be better -- I only need it in the yml workflow

**Comment by BobBorges** [comment]
This maybe https://github.com/marketplace/actions/semver-bump-action

**Comment by BobBorges** [comment]
I'm not totally excellent with poetry -- I need to get the version number as an env variable during the workflow. Will check what the best way to do that is.

**Comment by BobBorges** [comment]
OK for you now? @ninpnin

**Review by ninpnin — APPROVED** [review]
LGTM

**Pull request merged**
